/**
 * @see http://webpack.github.io/docs/configuration.html
 * for webpack configuration options
 */


/*
 * Banner Plugin is for code climate
 * @see https://gist.github.com/Ceane/9115471e90f4959e79da
 */
var webpack = require('webpack');
//var bannerPlugin = new webpack.BannerPlugin(
  //"/* jshint smarttabs:true, asi:true, curly: false, unused: false,  laxbreak: true, -W099, -W015 */ \n",
  //{ raw: true, entryOnly: true }
//)
var uglifyPlugin = new webpack.optimize.UglifyJsPlugin();


module.exports = {
  // 'context' sets the directory where webpack looks for module files you list in
  // your 'require' statements
  context: __dirname + '/src',

  plugins: [
    //bannerPlugin
  ],

  // 'entry' specifies the entry point, where webpack starts reading all
  // dependencies listed and bundling them into the output file.
  // The entrypoint can be anywhere and named anything - here we are calling it
  // '_application' and storing it in the 'javascripts' directory to follow
  // Rails conventions.
  entry: './index',

  // 'output' specifies the filepath for saving the bundled output generated by
  // wepback.
  // It is an object with options, and you can interpolate the name of the entry
  // file using '[name]' in the filename.
  // You will want to add the bundled filename to your '.gitignore'.
  output: {
    filename: '[name].js',
    // We want to save the bundle in the same directory as the other JS.
    path: __dirname + '/dist',
    library: "shortcut",
    libraryTarget: "umd"
  },

  // Turns on source maps
  // Prefix with a '#' to squash the FF warnings that say:
  // 'Using //@ to indicate sourceMappingURL pragmas is deprecated.
  // Use //# instead'
  //devtool: '#eval-source-map',

  // The 'module' and 'loaders' options tell webpack to use loaders.
  // @see http://webpack.github.io/docs/using-loaders.html
  module: modules(),

  resolve: {
    extensions: ['', '.js'],
  }
};





function modules(){
  return {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'},
      { test: /\.js$/, loader: 'eslint', exclude: /node_modules/ }
    ]
  };
}
